#!/bin/sh
# Build an OPAM package for a given OS/OCaml version combination.
# Requires an "opam-archive" container to be running.
# See the `run-opam-archive-container` script to do this.

LOGDIR=$1
shift
TAG=$1
shift
PKG=$1
J=2

if [ "$PKG" = "" ]; then
  echo "Usage: $0 <logdir> <tag> pkg"
  echo "e.g.: $0 logs avsm/docker-opam-build:ubuntu-4.04-ocaml-4.02.1 cohttp"
  exit 1
fi

# Record what actions the solver intends to take
META=$LOGDIR/$TAG/meta/${PKG}
sudo docker run --rm=true $TAG opam install --show-actions $PKG > ${META}.actions 2>&1
sudo docker run --rm=true $TAG opam show $PKG -f homepage > ${META}.homepage 2>&1
sudo docker run --rm=true $TAG opam show $PKG -f tags > ${META}.tags 2>&1
sudo docker run --rm=true $TAG opam show $PKG -f bug-reports > ${META}.bug-reports 2>&1
sudo docker run --rm=true $TAG opam show $PKG -f dev-repo > ${META}.dev-repo 2>&1
sudo docker run --rm=true $TAG opam show $PKG > ${META}.info 2>&1
# Do the actual build
LOG=$LOGDIR/$TAG/tmp/$PKG
starttime=`date +%s`
sudo docker run --rm=true --link opam-archive:opam-archive $TAG \
  /bin/sh -c "env OPAMVERBOSE=1 OPAMYES=1 OPAMJOBS=${J} opam depext -i $PKG" > $LOG 2>&1
RES=$?
endtime=`date +%s`
difftime=$(($endtime - $starttime))
echo $difftime > $LOGDIR/$TAG/meta/$PKG.buildtime
if [ $RES -eq 0 ]; then
  ln -nfs ../raw/$PKG $LOGDIR/$TAG/ok/$PKG
else
  ln -nfs ../raw/$PKG $LOGDIR/$TAG/err/$PKG
fi
mv $LOG $LOGDIR/$TAG/raw/$PKG
