#!/bin/sh
# Build an OPAM package for a given OS/OCaml version combination.
# Requires an "opam-archive" container to be running.
# See the `run-opam-archive-container` script to do this.

LOGDIR=$1
shift
TAG=$1
shift
PKG=$1
J=2

if [ "$PKG" = "" ]; then
  echo "Usage: $0 <logdir> <tag> pkg"
  echo "e.g.: $0 logs avsm/docker-opam-build:ubuntu-4.04-ocaml-4.02.1 cohttp"
  exit 1
fi

LOG=$LOGDIR/$TAG/raw/$PKG
sudo docker run --rm=true --link opam-archive:opam-archive $TAG \
  /bin/sh -c "opam repository add local http://opam-archive:8080 && env OPAMYES=1 OPAMJOBS=${J} opam installext $PKG" > $LOG
RES=$?
if [ $RES -eq 0 ]; then
  ln -nfs ../raw/$PKG $LOGDIR/$TAG/ok/$PKG
else
  ln -nfs ../raw/$PKG $LOGDIR/$TAG/err/$PKG
fi
